### ISSUE TITLE
Refactor notifications system

### ISSUE THREAD

**Issue by Amazing-Space-Invader** [secret-tech/frontend-ico-dashboard#131]
1. Remove redundant `react-notifications-system` and `react-redux-notification-system`.
2. Replace all notifications is sagas from RNS to blueprintjs notifications. Reference links below.

Example of usage blueprintjs notifications:
util: https://github.com/secret-tech/frontend-moon-wallet/blob/develop/src/utils/toaster/index.js
usage: https://github.com/secret-tech/frontend-moon-wallet/blob/develop/src/sagas/auth/signInSaga.js#L17

Install RRNS (just reverse and delete all) https://github.com/gor181/react-notification-system-redux#usage
Bluerprintjs toasts docs: http://blueprintjs.com/docs/v2/#core/components/toast

**Comment by ronnie173** [comment]
Anyone know what this error is?
![screen shot 2018-04-08 at 3 43 46 pm](https://user-images.githubusercontent.com/1444391/38472318-e8450780-3b43-11e8-9d2f-4eb6e31590a9.png)

**Comment by hlogeon** [comment]
Could you try to remove the JWT token and reload the page?

**Comment by kotokur** [comment]
@ronnie173 This is because of undefined JWT token. It's a problem with login using api mocks. The issue fixed here: https://github.com/secret-tech/frontend-ico-dashboard/pull/139. So far you can place JWT token from the mocks to the local storage manually
